name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create google-services.json file
        run: cat /home/runner/work/boardgamegeek4android/boardgamegeek4android/app/google-services.json | base64
      - name: Fill google-services.json file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/boardgamegeek4android/boardgamegeek4android/app/google-services.json
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build